<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '265802aa1829a0ae6299fe939799497f',
  'DATABASE_URL' => 'mysql://root:4uVexi9NqPXuQtyVkvcN@containers-us-west-174.railway.app:7923/railway',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
